shared: &shared
  - ".github/**"
  - "build-scripts/**"
docker:
  - *shared
  - ".dockerignore"
  - Dockerfile
  - "integration-tests/**"
rust: &rust
  - *shared
  - "**/*.toml"
  - ".cargo/**"
  - "crates/**"
  - Cargo.lock
deb:
  - *rust
  - LICENSE
  - README.md
