[package]
name = "docker-dns-rs"
# don't change this, it's updated before an actual build by update-version.sh
version = "0.0.0-development"
edition = "2021"
rust-version = "1.74.0"
authors = ["Kristof Mattei"]
description = "Rust end-to-end application"
license-file = "LICENSE"
categories = ["starter", "end-to-end"]
keywords = ["integrity", "end-to-end", "starter", "docker", "release"]
repository = "https://github.com/kristof-mattei/docker-dns-rs"

[lints.clippy]
# don't stop from compiling / running
all = "warn"
pedantic = "warn"
cargo = "warn"
# this one causes confusion when combining variables (`foo`) and
# dereferenced variables (`foo.bar`). The latter cannot be inlined
# so we don't inline anything
uninlined-format-args = { level = "allow", priority = 127 }

[lints.rust]
let_underscore_drop = { level = "deny", priority = 127 }
non_ascii_idents = { level = "deny", priority = 127 }

[profile.dev.package.backtrace]
opt-level = 3

[features]
coverage = []

[dependencies]
bytes = { version = "1.5.0", features = ["serde"] }
color-eyre = "0.6.2"

hyper = { version = "1.0.1", default-features = false }

hyper-util = { version = "0.1.0", default-features = false, features = [
    "client-legacy",
    "http1",
    "tokio",
] }

hyper-tls = { git = "https://github.com/kristof-mattei/hyper-tls", rev = "b29b0e99511d9745ff07e5922a0a66e3cb087567", features = [
    "vendored",
] }
hyper-unix-socket = "0.0.0-development"

http-body-util = "0.1.0"
percent-encoding = "2.3.0"

clap = { version = "4.4.0", features = ["derive"] }

tokio = { version = "1.33.0", features = [
    "rt-multi-thread",
    "macros",
    "time",
    "signal",
    "net",
] }

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = [
    "env-filter",
    "time",
    "tracing-log",
] }

serde_json = "1.0.107"
serde = { version = "1.0.190", features = ["derive"] }
tracing-error = "0.2.0"
tokio-util = "0.7.10"
http = "1.0.0"
url = "2.4.1"
pin-project-lite = "0.2.13"
futures-util = { version = "0.3", default-features = false }
tower-service = "0.3.2"
socket2 = "0.5.5"
async-stream = "0.3.5"
tokio-stream = "0.1.14"
once_cell = "1.18.0"
regex = "1.10.2"
ipnet = "2.9.0"
hickory-server = "0.24.0"

# We compile the Docker container with musl to get a static library. Smaller, faster.
# BUT that means that we need to include openssl
# Documentation on the syntax:
# https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies
[target.'cfg(all(target_arch = "x86_64", target_os="linux", target_env="musl"))'.dependencies]
# openssl = { version = "0.10.36", features = ["vendored"] }
